services:
  actual-http:
    build: .
    container_name: actual-http
    #network: host
    ports:
      - "5007:5007"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5007/health"]
      interval: 60s
      timeout: 10s
      retries: 3